### ISSUE TITLE
[BUG] cannot compile with BLTOUCH and ENDER5_OEM set

### ISSUE THREAD

**Issue by togeis** [th3dstudio/UnifiedFirmware#59]
Hi,
in current Configuration_backend.h you have set sanity checks:

--8<---

/**
 * TH3D Sanity Checks
 */
#if ENABLED(ABL_ENABLE) && ENABLED(S_CURVE_ACCELERATION)
  #error "S_CURVE_ACCELERATION is not compatible with ABL systems. Disable this and re-compile."
#endif

#if ENABLED(BLTOUCH) && DISABLED(CUSTOM_PROBE)
  #error "You must uncomment the CUSTOM_PROBE option in the EZABL probe mount section and then enter your mount offsets into the Custom Probe section."
#endif

--8<---

But "ENABLED(ABL_ENABLE) && ENABLED(S_CURVE_ACCELERATION)" is not caught, because ABL_ENABLED is not defined at this position. Moving to the end or after the probe setting will catch the condition.

And the second condition with  BLTOUCH is alway caught, because with using ENDER5_OEM i do not need to enable CUSTOM_PROBE. The probe position will be set in Configuration_backend.h.

So i cannot compile using BLTOUCH with ENDER5_OEM, and the S_CURVE_ACCELERATION Bug mentioned here: https://github.com/MarlinFirmware/Marlin/issues/19217#issuecomment-813353045 is still active.

Btw. the bug seems to be fixed in Marlin with  STRING_DISTRIBUTION_DATE "2021-04-04" .

Regards
Togeis

**Comment by th3dstudio** [comment]
ENDER5_OEM is only for EZABL not BL Touch. BL Touch always uses CUSTOM_PROBE and you have to enter in your probe offsets.

As for the sanity checks those are moved and will be changed in the next release.
