### ISSUE TITLE
Pull Request: Please update to Marlin 2.0.8.x

### ISSUE THREAD

**Issue by garaysantiago** [th3dstudio/UnifiedFirmware#60]
Pull Request: Please update to Marlin 2.0.8.x, it have many fixes. Thank you for your dedication!!!
(Note: "Pull requests" tab send me to Marlin official Github)

**Comment by houseofbugs** [comment]
It's done when it's done. If you want it do e quicker, you can make the updated yourself and make a proper pull request.

We keep up todate as quickly as we can and it's literally one person that does the code here. Please don't waste my time by making fake pull requests like this.
